### ISSUE TITLE
R programs generate Windows batch files

### ISSUE THREAD

**Issue by devilgate** [smallAreaHealthStatisticsUnit/rapidInquiryFacility#24]
The R script `Adj_Cov_Smooth_JRI.R` (and maybe others) tries to generate a Windows `.bat` file. That causes problems on non-Windows platforms.

It should ideally be conditional on running on Windows, or, if the script is necessary everywhere, it should generate appropriate ones for the platform. Given the simplicity of the batch file in question, a Bash script should run everywhere else.

Actually, considering that Windows now has a Unix environment built in, maybe a Bash script would run _everywhere_, including Windows.

**Comment by peterhambly** [comment]
This script is not run by the JRI; is is supplied so that end users can re-run the analysis. A Linux  version is also needed. so users are not limited in the platforms they can work on.

You need 64 bit Windows 10 for a Linux shell, and to turn the feature on.

I am hoping that since Canonical did it the shell and environment will be completely standard like the MingW/Msys shell I use now,

**Comment by devilgate** [comment]
Fair enough. PR #26 should fix the paths issue anyway.
